title: WangYifan's Homepage
page-top-title: Yifan Wang
top-section-bg-text: 3D Vision Researcher
home-subtitle: Yifan Wang&ensp;|&ensp;王一帆
copyright-text: '&copy; Wangyifan 2025-2026. All Rights Reserved.'

